export const StringConstant = {
  CONTACT_BOOK: 'Contact Book',
  PHONE_BOOK_HEADING: "Let's Connect With PhoneBook",
  LOGIN: 'Login',
  NEW_USER: 'New User? ',
  ALREADY_ACCOUNT: 'Already Account? ',
  REGISTER: 'Register',
  USER_ID: 'User Id',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL: 'Email',
  PHONE_NUMBER: 'Phone Number',
  ENTER_YOUR_USER_ID: 'Enter your User Id',
  ENTER_YOUR_FIRST_NAME: 'Enter your First Name',
  ENTER_YOUR_LAST_NAME: 'Enter your Last Name',
  ENTER_YOUR_EMAIL: 'Enter your Email',
  ENTER_YOUR_PHONE_NUMBER: 'Enter your Phone Number',
  FIRST_NAME_IS_REQUIRED: 'First Name is required',
  LAST_NAME_IS_REQUIRED: 'Last Name is required',
  EMAIL_IS_REQUIRED: 'Email is required',
  PHONE_NUMBER_IS_REQUIRED: 'Phone Number is required',
  PHONE_BOOK_REGISTRATION: 'Phone Book Registration',
  SIGN_UP: 'SignUp',
  MUST_BE_CHARACTER: 'Must be Character',
  NAME_MUST_BE: 'Name must be ',
  SPLASH: 'Splash',
  DIGIT: 'Digit',
  PHONE_NO_MUST_BE: 'Phone No. Must be',
  EDIT_PROFILE: 'EditProfile',
  TAB_NAVIGATION: 'TabNavigation',
  CONTACT: 'Contact',
  SIGN_OUT: 'Sign Out',
  MALE: 'Male',
  FEMALE: 'Female',
  OTHER: 'Other',
  CAMERA: 'Camera',
  CANCEL: 'Cancel',
  GALLERY: 'Gallery',
  CB: 'cb',
  YES: 'yes',
  NO: 'no',
  WANT_TO_DELETE: 'Are you sure you want to delete?',
  VIEW_USER: 'View User',
  ADD_FAVOURITE: 'Click to Add Favourite : ',
};

export const ApiPath = {
  signUp: 'https://crudapi.co.uk/api/v1/user',
  Login: 'https://crudapi.co.uk/api/v1/user',
};

export const ErrorConstant = {
  USER_ID_IS_REQUIRED: 'User ID is required',
  FIRST_NAME_IS_REQUIRED: 'First Name is required',
  LAST_NAME_IS_REQUIRED: 'Last Name is required',
  EMAIL_IS_REQUIRED: 'Email is required',
  PHONE_NUMBER_IS_REQUIRED: 'Phone Number is required',
  MUST_BE_CHARACTER: 'Must be Character',
  ENTER_VALID_EMAIL: 'Enter Valid Email',
  ENTER_VALID_MOBILE_NUMBER: 'Enter valid Mobile Number',
  CHARACTER: ' Character',
  NAME_MUST_BE: 'Name must be ',
  DIGIT: 'Digit',
  PHONE_NO_MUST_BE: 'Phone No. Must be',
  PLEASE_ENTER_VALID_USER_ID: 'Please enter Valid UserId',
  VALID_EMAIL_PASSWORD: ' Please Enter another email or phoneNumber',
  GENDER_REQUIRED: 'Gender is required',
  DOB_REQUIRED: 'DOB is required',
  COUNTRY_REQUIRED: 'country is required',
  STATE_REQUIRED: 'state is required',
  CITY_REQUIRED: 'city is required',
  PROFILE_IMAGE_REQUIRED: 'ProfileImage is required',
};
